- clean: [
    '~',
]

- link:
    ~/.gitconfig: gitconfig
    ~/.config/nvim: nvim
    ~/.tmux.conf: tmux.conf
    ~/.Xmodmap: Xmodmap

# TODO setup fisher with potential plugins (nvim.fish)

- shell:
    - [git submodule update --init --recursive, Installing submodules]
