- clean: [
    '~',
]

- link:
    ~/.gitconfig: gitconfig
    ~/.config/nvim: nvim
    ~/.tmux.conf: tmux.conf
    ~/.Xmodmap: Xmodmap
#  ~/.Xresources: Xresources
#  ~/.zshrc: zshrc

# TODO setup fisher with potential plugins (nvim.fish)

- shell:
    - [git submodule update --init --recursive, Installing submodules]
 #  - [~/.tmux/plugins/tpm/scripts/install_plugins.sh >/dev/null 2>&1, Installing tmux plugins]
    - ["vim +PlugUpdate +PlugClean! +qa", Installing and updating plugins]
