- clean: [
    '~',
]

- link:
    ~/.gitconfig: gitconfig
    ~/.config/nvim: nvim
    ~/.tmux.conf: tmux.conf
    ~/.Xmodmap: Xmodmap
    ~/.config/fish/config.fish: config.fish

# TODO setup fisher with potential plugins (nvim.fish)

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [cargo install zoxide --locked, Installing zoxide]
    - [cargo install alacritty --locked, Installing alacritty]
