- clean: [
    '~',
]

- link:
    ~/.gitconfig: gitconfig
    ~/.config/nvim: nvim
    ~/.tmux.conf: tmux.conf
    ~/.Xmodmap: Xmodmap
    ~/.config/fish/config.fish: config.fish
    ~/.config/alacritty/alacritty.toml: alacritty.toml
    ~/.config/fontconfig/fonts.conf: fonts.conf
    ~/phone.sh: phone.sh

# TODO setup fisher with potential plugins (nvim.fish)

- shell:
    - [fc-cache -vf]
    - [git submodule update --init --recursive, Installing submodules]
    - [cargo install zoxide --locked, Installing zoxide]
